/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/assets/models/ball.glb --o Ball.jsx 
*/

import { useSphere } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import { useControls } from 'leva'
import { useRef } from 'react'

export function Ball(props) {

  const ballBodyValue = useControls('ballBody', {
    width: { value: 0.0, min: -1, max: 1 }, // 차체의 넓이 X
    height: { value: 0.2, min: -1, max: 1 }, // 차체의 높이 Y
    front: { value: 0.1 * 2, min: -1, max: 1 }, // 차체의 길이 Z
  })

  const [ref] = useSphere(()=>({
    args:[0.15],
    mass:5,
    type: 'Dynamic',
    ...props
  }), useRef(null))

  const { nodes, materials } = useGLTF('/assets/models/ball.glb')
  return (
    <group {...props} dispose={null} ref={ref}>
      <group 
        scale={0.15} 
        position={[0, -0.153, -0.004]}
        // position={[ballBodyValue.width, ballBodyValue.height, ballBodyValue.front * 2]}
        
      >
        <mesh geometry={nodes.beach_ball_red_0_1.geometry} material={materials.material} />
        <mesh geometry={nodes.beach_ball_red_0_2.geometry} material={materials.blue} />
        <mesh geometry={nodes.beach_ball_red_0_3.geometry} material={materials.white} />
        <mesh geometry={nodes.beach_ball_red_0_4.geometry} material={materials.yellow} />
      </group>
    </group>
  )
}


