/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/assets/models/tree.glb --o Tree.jsx 
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'

export function Tree(props) {
  const { nodes, materials } = useGLTF('/assets/models/tree.glb')

  const [ref] = useBox(()=>({
    args:[0.3, 1, 0.3],
    type:'Static',
    ...props,
  }))
  return (
    <group {...props} dispose={null}>
      <mesh scale={0.2} geometry={nodes.tree.geometry} material={materials['Material.003']} position={[0, 0, 0]} rotation={[-1.555, 0, 0]} />
    </group>
  )
}
